extern float minDist;
extern bool isNear;
extern bool washing;
extern bool moving;
extern bool welcome;
extern volatile bool ready;
extern bool closing;
extern volatile bool sleeping;
extern bool leaving;
extern bool gateState;